### ISSUE TITLE
Git flow: release finish doesn't work

### ISSUE THREAD

**Issue by sebdah** [SublimeGit/SublimeGit#135] opened 2014-05-09 05:04 UTC
I was trying to run a release finish when using the git-flow commands. However you're required to set a tag message and SublimeGit did not offer me an input field to do that, so I had to run the release finish in the console instead. Here's the output from Sublime console:

    Switched to branch 'master'
    Your branch is up-to-date with 'origin/master'.
    Merge made by the 'recursive' strategy.
     docs/command_line_options.rst                  |  39 +++-
     docs/conf.py                                   |   4 +-
     docs/configuration_options.rst                 |   8 +
     docs/example_configuration.rst                 |   2 +-
     docs/images/reset-consecutive-counter.png      | Bin 0 -> 27912 bytes
     docs/release_notes.rst                         |  17 ++
     dynamic_dynamodb/__init__.py                   |  76 ++++++--
     dynamic_dynamodb/config/__init__.py            |  17 +-
     dynamic_dynamodb/config/command_line_parser.py |  28 ++-
     dynamic_dynamodb/config/config_file_parser.py  |  48 +++++
     dynamic_dynamodb/core/gsi.py                   | 242 ++++++++++++++++++-------
     dynamic_dynamodb/core/table.py                 | 229 +++++++++++++++++------
     dynamic_dynamodb/dynamic-dynamodb.conf         |   2 +-
     13 files changed, 559 insertions(+), 153 deletions(-)
     create mode 100644 docs/images/reset-consecutive-counter.png
    Vim: Warning: Output is not to a terminal
    Vim: Warning: Input is not from a terminal
    [m[m[0m[H[2J[24;1H"~/git/sebdah/dynamic-dynamodb/.git/TAG_EDITMSG" 4L, 68C[1;1H[1m[317m[4190m .g/TAG_EDITMSG [0m[3190m[4234m[0m[385m[4234m                                                     [0m[3214m[4234m[0m[1m[3232m[4214m buffers [0m[2;1H[33m  1
      2 [0m[34m#[0m
    [33m  3 [0m[34m# Write a tag message[0m
    [33m  4 [0m[34m# Lines starting with '#' will be ignored.[0m

I was doing this on an Mac OS X with everything fully upgraded.

**Comment by michaelpedersen** [comment] 2015-02-08 15:48
This seems to be a duplicate of #51 and #63. Closing.

**Closed by michaelpedersen** 2015-02-08 15:48 UTC
