### ISSUE TITLE
Add selected hunk

### ISSUE THREAD

**Issue by FredyC** [SublimeGit/SublimeGit#133] opened 2014-04-29 06:47 UTC
This is feature of the https://github.com/kemayo/sublime-text-git. Simply it allows to select text in the opened file and by invoking this command it adds to the stage just that selected text (if there is any change). I am very used to this. Would it be possible to add something similar ?

**Comment by michaelpedersen** [comment] 2015-02-08 15:46
Duplicate of #11

**Closed by michaelpedersen** 2015-02-08 15:46 UTC
