### ISSUE TITLE
goto source file from diff (feature request)

### ISSUE THREAD

**Issue by KES777** [SublimeGit/SublimeGit#191] opened 2015-04-02 17:41 UTC
when I look diff 
allow me to goto source file where changes are make when press 'g' button

This will allow me make another changes.
For example I notice BUG and want correct it.

**Comment by raunaqgupta** [comment] 2016-02-12 11:47
I want to +1 this request as well as elaborate on what I want the feature to work out:

Searching a file (or the entire repo) inside SublimeText opens up a new tab with all the files and the corresponding highlighted lines much like how `Git: Diff` works currently. Clicking on a particular line should open up that file and take the user to that line in much the same way how the search results tab works.

**Comment by dacook** [comment] 2016-06-07 02:30
Thanks for clarifying this @raunaqgupta -- I too would like to request this.

We'd need a bit of logic to process the `git diff` output  to get the filename and line number, then run something like this:
`self.view.window().open_file("%s:%d:%d" (filename, line, column), sublime.ENCODED_POSITION)`

**Comment by miped** [comment] 2016-07-16 01:53
To stay consistent, this should probably happen by clicking `[enter]` as it does in the status view. Last i checked, using the mouse was a bit of a pain, but i'll have another look. That was a couple of ST versions ago.

**Comment by miped** [comment] 2016-07-16 01:56
Actually, this is a duplicate of #74. Closing.

**Closed by miped** 2016-07-16 01:56 UTC
Labels: enhancement
