### ISSUE TITLE
offer better merge conflict support, integrate with sublimerge?

### ISSUE THREAD

**Issue by maxheld83** [SublimeGit/SublimeGit#199] opened 2015-05-14 14:57 UTC
When a merge raises conflicts, SublimeGit just offers a pretty (angry) pop-up informing you of the conflicting files.
It'd be super nice if we could have some more support, and maybe integration with a `git mergetool`, such as Sublimerge.
(Currently, even as a custom command, `git mergetool` does not appear to work -> #198).

Ideally, SublimeGit would ask me what kind of mergetool I'd like to use (including Sublimerge), and then hold my hands during the resolution.

The [Merge Conflicts](https://atom.io/packages/merge-conflicts) package for Atom does a pretty good job of this.

I'll try to get the Sublimerge dev in on this, doesn't have a repo/issue tracker, unfortunately.

**Comment by miped** [comment] 2016-07-16 01:49
@maxheld83 i've already been in contact with the author of Sublimerge (a long time ago), and know how to go about it. This is a duplicate of #163

**Closed by miped** 2016-07-16 01:49 UTC
